# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!
target 'NewTcpApp' do
  pod 'SVProgressHUD'
  pod 'SwiftyJSON'
  pod 'HandyJSON'
  pod 'IQKeyboardManager'
  pod 'MJRefresh'
  pod 'Toast'
  pod 'SnapKit', '~> 4.2.0'
  pod 'TZImagePickerController'
#  pod 'SDPhotoBrowser'
    # 集成新浪微博
  pod 'UMCCommon'
  pod 'UMCShare/Social/Sina'
  pod 'UMCShare/Social/QQ'
#    pod 'UMCShare/Social/WeChat'
#    pod 'Realm'
  pod 'AFNetworking'
  pod 'SDWebImage','~> 4.4.3'
  pod 'Masonry'
  pod 'WechatOpenSDK'
#    pod 'RongCloudIM/IMLib','~> 2.9.25'
#    pod 'RongCloudIM/IMKit','~> 2.9.25'
#    pod 'RongCloudRTC/RongCallLib', '~> 2.9.25'
#    pod 'RongCloudRTC/RongCallKit', '~> 2.9.25'
  pod 'RongCloudIM/IMLib'
  pod 'RongCloudIM/IMKit'
  pod 'RongCloudRTC/RongCallLib'
  pod 'RongCloudRTC/RongCallKit'
  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
  pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
  post_install do |installer|
       installer.pods_project.targets.each do |target|
             target.build_configurations.each do |config|
                   config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
             end
       end
   end
end
