# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!
target 'NewTcpApp' do
    # 集成新浪微博
    pod 'UMCShare/Social/Sina'
    pod 'UMCShare/Social/QQ'
    pod 'UMCShare/Social/WeChat'
    pod 'Realm','3.18.0'
    pod 'AFNetworking'
    pod 'SDWebImage','~> 4.4.3'
    pod 'Masonry'
#    pod 'WechatOpenSDK'
    pod 'RongCloudIM/IMLib','~> 2.9.25'
    pod 'RongCloudIM/IMKit','~> 2.9.25'
    pod 'RongCloudRTC/RongCallLib', '~> 2.9.25'
    pod 'RongCloudRTC/RongCallKit', '~> 2.9.25'
#    pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
#    pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
end
